name: Playwright Tests
on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_set:
          - e2e
          - api
    steps:
    - name: Get code
      uses: actions/checkout@v3

    - name: Install Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run tests
      run: |
          if [ ${{ matrix.test_set }} == 'e2e' ]; then
            npx playwright test e2e
          elif [ ${{ matrix.test_set }} == 'api' ]; then
            npx playwright test api
          fi
    - name: Publish HTML Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
