name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v3

    - name: Install Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
  e2e-tests:
    timeout-minutes: 60
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Run Playwright tests e2e
      run: npx playwright e2e e2e

    - name: Publish HTML Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  api-tests:
    timeout-minutes: 60
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Run Playwright tests api
      run: npx playwright e2e api
    - name: Publish HTML Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30